// swift-tools-version: 6.2
//
// Package.swift — builds the native macOS app (SwiftUI + AppKit) and the C
// client library it talks through. Lives at the repo root so targets can
// reference the engine's client sources; the native driver/engine themselves
// stay on CMake (this package never compiles them).
//
//   swift build                    # CRoomcutClient + Roomcut (menu-bar app)
//   swift run Roomcut --selftest   # headless: connect to the engine, verify
//   scripts/build-app.sh           # assemble build/Roomcut.app (LSUIElement)
import PackageDescription

let package = Package(
    name: "Roomcut",
    platforms: [.macOS(.v26)],
    targets: [
        // Plain-C client API over the engine's Mach control plane. Wraps the
        // C++ transport (Control.cpp) + builtin preset table behind
        // engine/client/include/roomcut_client.h — the only header Swift sees.
        .target(
            name: "CRoomcutClient",
            path: "engine",
            sources: [
                "src/Control.cpp",
                "client/ClientShim.cpp",
                "client/CoreAudioDevices.cpp",
                "client/EngineConnection.cpp",
            ],
            publicHeadersPath: "client/include",
            cxxSettings: [
                .headerSearchPath("include"),
                .headerSearchPath("../shared/protocol"),
                .headerSearchPath("../core"),
                .headerSearchPath("../core/dsp"),     // bare ChainParams.hpp include
                .headerSearchPath("../core/presets"), // (matches engine/CMakeLists)
            ],
            linkerSettings: [
                // The client device module reads/writes HAL properties in-process.
                .linkedFramework("CoreAudio"),
                .linkedFramework("CoreFoundation"),
            ]
        ),
        .target(
            name: "RoomcutPresentationCore",
            path: "apps/macos/Roomcut",
            exclude: [
                "SoundHistoryControls.swift",
                "SoundEditMenuController.swift",
                "SoundSnapshot.swift",
                "SoundComparison.swift",
                "SoundEditor.swift",
                "ParameterWriter.swift",
                "PresetStore.swift",
                "AppPreferences.swift",
                "SavedPreset.swift",
                "PresetLibrary.swift",
                "DeviceCommandWriter.swift",
                "BypassOverride.swift",
                "BypassWriter.swift",
                "EnginePoller.swift",
                "RefreshPlan.swift",
                "NowPlayingStream.swift",
                "NowPlayingLyrics.swift",
                "DeviceReadCoordinator.swift",
                "DeviceReadback.swift",
                "RoomcutMeters.swift",
                "EngineClient.swift",
                "EngineDeviceTypes.swift",
                "EngineStatus.swift",
                "EngineParameters.swift",
                "DeviceListWatcher.swift",
                "HeadTrackingService.swift",
                "HeadYawTracker.swift",
                "RoomcutViewModel.swift",
                "RoomcutViewModel+Presets.swift",
                "RoomcutViewModel+Settings.swift",
                "RoomcutViewModel+Spatial.swift",
                "RoomcutViewModel+Parametric.swift",
                "RoomcutViewModel+SoundHistory.swift",
                "main.swift",
                "RoomcutApp.swift",
                "RoomcutMainWindow.swift",
                "AppDelegate.swift",
                "MenuContent.swift",
                "MainWindow.swift",
                "WindowChrome.swift",
                "RoomcutAppCanvas.swift",
                "RoomcutWindowChromeViews.swift",
                "RoomcutTopBar.swift",
                "RoomcutBottomTabBar.swift",
                "HomeTab.swift",
                "SpaceTab.swift",
                "SpatialFieldView.swift",
                "SpatialFieldScene.swift",
                "RoomTuneInputScanner.swift",
                "RoomTuneAnalysis.swift",
                "RoomTuneResponse.swift",
                "RoomTuneSignal.swift",
                "RoomTuneAudioFile.swift",
                "RoomTunePCM.swift",
                "RoomTuneWorkflow.swift",
                "RoomTuneWorkQueue.swift",
                "RoomTuneRound.swift",
                "MeasurementCorrection.swift",
                "RoomTuneRecorder.swift",
                "RoomTuneAudioSession.swift",
                "RoomTuneSweep.swift",
                "RoomTuneMeasurement.swift",
                "RoomTuneTab.swift",
                "InspectTab.swift",
                "SettingsTab.swift",
                "SettingsSelectors.swift",
                "SettingsMaintenance.swift",
                "DriverMaintenance.swift",
                "NowPlayingView.swift",
                "NowPlayingCards.swift",
                "NowPlayingPieces.swift",
                "NowPlayingBackdrop.swift",
                "NowPlayingHalo.swift",
                "NowPlayingChrome.swift",
                "NowPlayingLyricViews.swift",
                "NowPlayingMonitor.swift",
                "NowPlayingArtwork.swift",
                "NowPlayingElapsed.swift",
                "NowPlayingLyricsFetch.swift",
                "NowPlayingControls.swift",
                "NowPlayingPayload.swift",
                "LRCLIBClient.swift",
                "LRCLIBCache.swift",
                "StringHelpers.swift",
                "RoomcutGlassStyle.swift",
                "RoomcutBackgroundLayer.swift",
                "RoomcutMacroControls.swift",
                "EqPresetPicker.swift",
                "PresetTreeView.swift",
                "MacroKnob.swift",
                "EqMiniCurve.swift",
                "AdvancedControls.swift",
                "EqualizerView.swift",
                "ParametricEditor.swift",
                "AudioStatusView.swift",
                "UIFixture.swift",
                "AppLaunch.swift",
                "SelfTest.swift",
            ],
            sources: [
                "RoomcutPresentation.swift",
                "RoomcutMainPresentation.swift",
                "RoomcutTheme.swift",
            ],
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        .target(
            name: "RoomcutCore",
            dependencies: ["CRoomcutClient", "RoomcutPresentationCore"],
            path: "apps/macos/Roomcut",
            exclude: [
                "SoundHistoryControls.swift",
                "main.swift",
                "RoomcutApp.swift",
                "RoomcutMainWindow.swift",
                "AppDelegate.swift",
                "MenuContent.swift",
                "MainWindow.swift",
                "WindowChrome.swift",
                "RoomcutAppCanvas.swift",
                "RoomcutWindowChromeViews.swift",
                "RoomcutTopBar.swift",
                "RoomcutBottomTabBar.swift",
                "HomeTab.swift",
                "SpaceTab.swift",
                "SpatialFieldView.swift",
                "SpatialFieldScene.swift",
                "RoomTuneInputScanner.swift",
                "RoomTuneRecorder.swift",
                "RoomTuneAudioSession.swift",
                "RoomTuneSweep.swift",
                "RoomTuneMeasurement.swift",
                "RoomTuneTab.swift",
                "InspectTab.swift",
                "SettingsTab.swift",
                "SettingsSelectors.swift",
                "SettingsMaintenance.swift",
                "DriverMaintenance.swift",
                "NowPlayingView.swift",
                "NowPlayingCards.swift",
                "NowPlayingPieces.swift",
                "NowPlayingBackdrop.swift",
                "NowPlayingHalo.swift",
                "NowPlayingChrome.swift",
                "NowPlayingLyricViews.swift",
                "NowPlayingMonitor.swift",
                "NowPlayingArtwork.swift",
                "NowPlayingElapsed.swift",
                "NowPlayingLyricsFetch.swift",
                "NowPlayingControls.swift",
                "RoomcutGlassStyle.swift",
                "RoomcutBackgroundLayer.swift",
                "RoomcutMacroControls.swift",
                "EqPresetPicker.swift",
                "PresetTreeView.swift",
                "MacroKnob.swift",
                "EqMiniCurve.swift",
                "AdvancedControls.swift",
                "EqualizerView.swift",
                "ParametricEditor.swift",
                "AudioStatusView.swift",
                "UIFixture.swift",
                "AppLaunch.swift",
                "SelfTest.swift",
                "RoomcutPresentation.swift",
                "RoomcutMainPresentation.swift",
                "RoomcutTheme.swift",
            ],
            sources: [
                "SoundEditMenuController.swift",
                "SoundSnapshot.swift",
                "SoundComparison.swift",
                "SoundEditor.swift",
                "ParameterWriter.swift",
                "PresetStore.swift",
                "AppPreferences.swift",
                "SavedPreset.swift",
                "PresetLibrary.swift",
                "DeviceCommandWriter.swift",
                "BypassOverride.swift",
                "BypassWriter.swift",
                "EnginePoller.swift",
                "RefreshPlan.swift",
                "NowPlayingStream.swift",
                "NowPlayingLyrics.swift",
                "DeviceReadCoordinator.swift",
                "DeviceReadback.swift",
                "RoomcutMeters.swift",
                "EngineClient.swift",
                "EngineDeviceTypes.swift",
                "EngineStatus.swift",
                "EngineParameters.swift",
                "DeviceListWatcher.swift",
                "HeadTrackingService.swift",
                "HeadYawTracker.swift",
                "RoomcutViewModel.swift",
                "RoomcutViewModel+Presets.swift",
                "RoomcutViewModel+Settings.swift",
                "RoomcutViewModel+Spatial.swift",
                "RoomcutViewModel+Parametric.swift",
                "RoomcutViewModel+SoundHistory.swift",
                "NowPlayingPayload.swift",
                "LRCLIBClient.swift",
                "LRCLIBCache.swift",
                "StringHelpers.swift",
                "RoomTuneAnalysis.swift",
                "RoomTuneResponse.swift",
                "RoomTuneSignal.swift",
                "RoomTuneAudioFile.swift",
                "RoomTunePCM.swift",
                "RoomTuneWorkflow.swift",
                "RoomTuneWorkQueue.swift",
                "RoomTuneRound.swift",
                "MeasurementCorrection.swift",
            ],
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        // The menu-bar app: SwiftUI MenuBarExtra UI over an AppKit accessory
        // activation policy. `--selftest` exercises the client headlessly.
        .executableTarget(
            name: "Roomcut",
            dependencies: ["CRoomcutClient", "RoomcutCore", "RoomcutPresentationCore"],
            path: "apps/macos/Roomcut",
            exclude: [
                "SoundEditMenuController.swift",
                "SoundSnapshot.swift",
                "SoundComparison.swift",
                "SoundEditor.swift",
                "ParameterWriter.swift",
                "PresetStore.swift",
                "AppPreferences.swift",
                "SavedPreset.swift",
                "PresetLibrary.swift",
                "DeviceCommandWriter.swift",
                "BypassOverride.swift",
                "BypassWriter.swift",
                "EnginePoller.swift",
                "RefreshPlan.swift",
                "NowPlayingStream.swift",
                "NowPlayingLyrics.swift",
                "DeviceReadCoordinator.swift",
                "DeviceReadback.swift",
                "RoomcutMeters.swift",
                "RoomTuneAnalysis.swift",
                "RoomTuneResponse.swift",
                "RoomTuneSignal.swift",
                "RoomTuneAudioFile.swift",
                "RoomTunePCM.swift",
                "RoomTuneWorkflow.swift",
                "RoomTuneWorkQueue.swift",
                "RoomTuneRound.swift",
                "MeasurementCorrection.swift",
                "EngineClient.swift",
                "EngineDeviceTypes.swift",
                "EngineStatus.swift",
                "EngineParameters.swift",
                "DeviceListWatcher.swift",
                "HeadTrackingService.swift",
                "HeadYawTracker.swift",
                "RoomcutViewModel.swift",
                "RoomcutViewModel+Presets.swift",
                "RoomcutViewModel+Settings.swift",
                "RoomcutViewModel+Spatial.swift",
                "RoomcutViewModel+Parametric.swift",
                "RoomcutViewModel+SoundHistory.swift",
                "RoomcutPresentation.swift",
                "RoomcutMainPresentation.swift",
                "RoomcutTheme.swift",
                "NowPlayingPayload.swift",
                "LRCLIBClient.swift",
                "LRCLIBCache.swift",
                "StringHelpers.swift",
            ],
            sources: [
                "SoundHistoryControls.swift",
                "main.swift",
                "RoomcutApp.swift",
                "RoomcutMainWindow.swift",
                "AppDelegate.swift",
                "MainWindow.swift",
                "WindowChrome.swift",
                "RoomcutAppCanvas.swift",
                "RoomcutWindowChromeViews.swift",
                "RoomcutTopBar.swift",
                "RoomcutBottomTabBar.swift",
                "HomeTab.swift",
                "SpaceTab.swift",
                "SpatialFieldView.swift",
                "SpatialFieldScene.swift",
                "RoomTuneInputScanner.swift",
                "RoomTuneRecorder.swift",
                "RoomTuneAudioSession.swift",
                "RoomTuneSweep.swift",
                "RoomTuneMeasurement.swift",
                "RoomTuneTab.swift",
                "InspectTab.swift",
                "SettingsTab.swift",
                "SettingsSelectors.swift",
                "SettingsMaintenance.swift",
                "DriverMaintenance.swift",
                "NowPlayingView.swift",
                "NowPlayingCards.swift",
                "NowPlayingPieces.swift",
                "NowPlayingBackdrop.swift",
                "NowPlayingHalo.swift",
                "NowPlayingChrome.swift",
                "NowPlayingLyricViews.swift",
                "NowPlayingMonitor.swift",
                "NowPlayingArtwork.swift",
                "NowPlayingElapsed.swift",
                "NowPlayingLyricsFetch.swift",
                "NowPlayingControls.swift",
                "RoomcutGlassStyle.swift",
                "RoomcutBackgroundLayer.swift",
                "RoomcutMacroControls.swift",
                "EqPresetPicker.swift",
                "PresetTreeView.swift",
                "MacroKnob.swift",
                "EqMiniCurve.swift",
                "AdvancedControls.swift",
                "MenuContent.swift",
                "EqualizerView.swift",
                "ParametricEditor.swift",
                "AudioStatusView.swift",
                "UIFixture.swift",
                "AppLaunch.swift",
                "SelfTest.swift",
            ],
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        .testTarget(
            name: "RoomcutTests",
            dependencies: ["RoomcutCore", "RoomcutPresentationCore"],
            path: "apps/macos/RoomcutTests",
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
    ],
    cxxLanguageStandard: .cxx17
)
